import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/providers/StoreProvider";
import AllRecipesProvider from "@/providers/AllRecipesProvider";
import { Roboto } from "next/font/google";


const roboto = Roboto({
  subsets: ["latin", 'cyrillic'],
  weight: ["400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreProvider>
          <AllRecipesProvider>
            {children}
          </AllRecipesProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
